### ISSUE TITLE
Clinic appointment type lookup

### ISSUE THREAD

**Issue by bobintetley** [sheltermanager/asm3#1317]
As well as the free text reason for appointment, at least one user would like a select/dropdown of reasons/type of  appointment so that they could standardise them.

clinicappointment.ClinicTypeID

clinictype ( ID, ClinicTypeName, ClinicTypeDescription )

**Comment by bobintetley** [comment]
Default values for the table: Consultation, Followup, Prescription, Surgery

**Comment by Tetzor** [comment]
added clinictypename to clinic_appointments_between_two_dates.rep and clinic_appointments_mailmerge.rep
