### ISSUE TITLE
Embedding adoptable animals into Wordpress site

### ISSUE THREAD

**Issue by KatBunny23** [sheltermanager/asm3#1455]
Hi, 

We are developing our website and I am trying to link our ASM to it to show our current animals. We are definitely not website developers so this is all totally alien to us. 

I have followed the guides on how to do this. However, when I copy the HTML codes that show in the publisher section, they just display on our website as the codes themselves. I'm guessing I am missing something that I need to add in to those codes, but no idea what. Could someone please advise?

**Comment by bobintetley** [comment]
This is not a software development issue, please use the discussions area above to ask questions about open source ASM. If you are a sheltermanager customer, please email SM support at help@sheltermanager.com including your account number
