### ISSUE TITLE
Nicer report header

### ISSUE THREAD

**Issue by bobintetley** [sheltermanager/asm3#1553]
The default report header is ancient and looks naff. Add a bit of colour, use collapsed borders on tables.

You did a job for a customer recently that used the sorttable widget to make the report tables sortable. The header is below:

```
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>$$TITLE$$</title>
<script src="https://cdn.jsdelivr.net/npm/sorttable@1.0.2/sorttable.min.js"></script>
<style>
  * {
    font-family:Arial, Helvetica, sans-serif;
    }
  h2 {
    color:#837200
    padding:10px 0 0 0;
    }
  h3, h4, h5 {
    color:#1F252C
    }
  table {
    border: 1px solid black; 
    border-collapse: collapse;
    padding:0;
    }
  th, td {
    padding:7px 10px; 
    vertical-align:middle;
    }
  thead {
    background-color:#189CA1; 
    color:#003473;
    text-align:left; 
    font-weight:bold;
    }
  tfoot {
    background-color:#189CA1; 
    color:#003473; 
    text-align:center; 
    font-weight:bold;
    }
  tbody {
    text-align:left;
    }
  .header {
    width: 100%;
  	display: flex;
    justify-content: space-between;
  	align-items: center;
    margin: 0 0 15px 0;
    }
  .content-left {
    float: left;
	align-self: center;
    padding: 0;
    }
  .content-right {
    float: right;
	align-self: center;
    padding: 0;
	}
  .content {
    font-size: 1.75em;
    font-weight: bold;
	}
</style>
</head>
  
<body>
  
<div class="header">
    <div class="content-left">
        <img src="image?db=$DATABASE&mode=dbfs&id=/reports/logo.jpg" height="42">
    </div>
    <div class="content">
      <center>$$TITLE$$</center>
    </div>
    <div class="content-right">
    </div>
</div>
```

The footer:

```
<script>
$("table").addClass("sortable");
</script>
</body>
</html>
```

**Comment by thisis-satvik** [comment]
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>$$TITLE$$</title>
<script src="https://cdn.jsdelivr.net/npm/sorttable@1.0.2/sorttable.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<style>
  * {
    font-family:Arial, Helvetica, sans-serif;
  }
  h2 {
    color:#837200;
    padding:10px 0 0 0;
  }
  h3, h4, h5 {
    color:#1F252C;
  }
  table {
    border: 1px solid #003473;
    border-collapse: collapse;
    padding:0;
  }
  th, td {
    padding:7px 10px;
    vertical-align:middle;
    border: 1px solid #003473;
  }
  thead {
    background-color:#189CA1;
    color:#FFFFFF;
    text-align:left;
    font-weight:bold;
  }
  tfoot {
    background-color:#189CA1;
    color:#FFFFFF;
    text-align:center;
    font-weight:bold;
  }
  tbody {
    text-align:left;
  }
  .header {
    width: 100%; 
    display: flex;
    justify-content: space-between; 
    align-items: center;
    margin: 0 0 15px 0;
    background-color: #003473;
    color: #FFFFFF;
  }
  .content-left {
    float: left;
    align-self: center;
    padding: 0;
  }
  .content-right {
    float: right;
    align-self: center;
    padding: 0;
  }
  .content {
    font-size: 1.75em;
    font-weight: bold;
    text-align: center;
    width: 100%;
  }
</style>
<script>
$(document).ready(function(){
  $("table").addClass("sortable");
});
</script>
</head>
<body>
  <div class="header">
    <div class="content-left">
      <img src="image?db=$DATABASE&mode=dbfs&id=/reports/logo.jpg" height="42">
    </div>
    <div class="content">$$TITLE$$</div>
    <div class="content-right"></div>
  </div>
</body>
</html>

**Comment by thisis-satvik** [comment]
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>$$TITLE$$</title>
<script src="https://cdn.jsdelivr.net/npm/sorttable@1.0.2/sorttable.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<style>
  * {
    font-family:Arial, Helvetica, sans-serif;
  }
  h2 {
    color:#837200;
    padding:10px 0 0 0;
  }
  h3, h4, h5 {
    color:#1F252C;
  }
  table {
    border: 1px solid #003473;
    border-collapse: collapse;
    padding:0;
  }
  th, td {
    padding:7px 10px;
    vertical-align:middle;
    border: 1px solid #003473;
  }
  thead {
    background-color:#189CA1;
    color:#FFFFFF;
    text-align:left;
    font-weight:bold;
  }
  tfoot {
    background-color:#189CA1;
    color:#FFFFFF;
    text-align:center;
    font-weight:bold;
  }
  tbody {
    text-align:left;
  }
  .header {
    width: 100%; 
    display: flex;
    justify-content: space-between; 
    align-items: center;
    margin: 0 0 15px 0;
    background-color: #003473;
    color: #FFFFFF;
  }
  .content-left {
    float: left;
    align-self: center;
    padding: 0;
  }
  .content-right {
    float: right;
    align-self: center;
    padding: 0;
  }
  .content {
    font-size: 1.75em;
    font-weight: bold;
    text-align: center;
    width: 100%;
  }
</style>
<script>
$(document).ready(function(){
  $("table").addClass("sortable");
});
</script>
</head>
<body>
  <div class="header">
    <div class="content-left">
      <img src="image?db=$DATABASE&mode=dbfs&id=/reports/logo.jpg" height="42">
    </div>
    <div class="content">$$TITLE$$</div>
    <div class="content-right"></div>
  </div>
</body>
</html>
