### ISSUE TITLE
Homechecks performed between two dates

### ISSUE THREAD

**Issue by bobintetley** [sheltermanager/asm3#197]
New report for homechecks performed between two dates. Include details of the homechecker and the person being homechecked. 

Attempt to find the most recent reservation for the person as a guess to which animal they were being homechecked for. Include some animal info if available. 

Calculate the difference between the reservation date (if available) and the datelasthomechecked to get a number of days turnaround on doing the homecheck. Use {AVG} to show an average turnaround for the period reported on.

You can calculate the difference between two dates with this expression: 
EXTRACT(DAY FROM NewerDate - OlderDate)::integer  AS days 

owner.HomeCheckedBy contains the owner ID of the homechecker, IDCheck = 1 is homechecked and DateLastHomeChecked is the date of the most recent check

**Comment by bobintetley** [comment]
Using EXTRACT makes the report PostgreSQL only, so make sure that's in the database version/string of the report (eg: 2870/PostgreSQL)

**Comment by bobintetley** [comment]
notify zb1244 on completion

**Comment by Tetzor** [comment]
Hey dude sorry i havent been on i got sucked into final fantasy and had 
a lot on at home. Is there any chance we could get together for an hour 
or two for  bit of coaching one afternoon. The difficulty seems to have 
gone up a notch on the latest ticket , i could do with a bit of time 
with you on building more complex queries like this and how to structure 
them.  We are overdue a game of snooker too! hav you been watching the 
championships on BBC2?

**Comment by bobintetley** [comment]
Start at the owner table to get the homecheckedby and datelasthomechecked for filtering and display.

Use a left join to the adoption table to get the reservations. Use a subquery to get the latest reservation for that person and complete the join, once you've got that you can get the animal. Eg:

SELECT * FROM owner
LEFT OUTER JOIN adoption ON adoption.ID = (SELECT MAX(ID) FROM adoption WHERE OwnerID = owner.ID AND MovementType = 0)
LEFT OUTER JOIN animal ON adoption.AnimalID = animal.ID
WHERE DateLastHomeChecked >= '$ASK DATE Homechecks between$' AND DateLastHomeChecked <= '$ASK DATE and $'

So, the first join is finding the latest reservation for that person and joining it to our owner table, the second join is getting the animal for the first join.
