### ISSUE TITLE
PDF417 USDL scanning

### ISSUE THREAD

**Issue by bobintetley** [sheltermanager/asm3#23]
PDF417 barcodes are popular in the US and encode driving license information. There are apps that will scan the data on mobile phones. We no longer have a mobile app, is it possible to scan these barcodes with something browser based on mobile so that it can be used to fill out person info?

**Comment by bobintetley** [comment]
moved to smcom_mobile

**Comment by bobintetley** [comment]
we still get requests for this, and it never was supported on smcom_mobile (which is now dead). Perhaps we could revive it and look at it again for the newer mobile UI

**Comment by bobintetley** [comment]
There is one javascript decoder I could find on github, however it does not sound like it's very reliable. https://github.com/PeculiarVentures/js-zxing-pdf417

There's also a Python decoder, but that would mean sending the image data to the server for decoding.

This might be worth trying, but it might not have a good chance of success.

**Comment by adamdspencer77** [comment]
Experimented with various JS and Python barcode readers. All were unable to cope with a photo of a license. Can't see this being reliable. Abandoned.
