### ISSUE TITLE
Occupancy report

### ISSUE THREAD

**Issue by bobintetley** [sheltermanager/asm3#971]
A report that is similar to Location and Unit mode in that it shows all locations and units with their occupancy and empty ones. Gives totals for occupied and unoccupied units and a percentage occupation rate.

**Comment by bobintetley** [comment]
Use regexp_split_to_table to turn the units string into results, eg:

select locationname, regexp_split_to_table(units, '[,]') as unit from internallocation;

Just need to strip the unit and can then outer join to the animal table to find who is in each unit.

**Comment by Tetzor** [comment]
Added "location_and_unit_with_animals.rep"
